### ISSUE TITLE
discussion: recommended way to authenticate requests

### ISSUE THREAD

**Issue by srizvi** [9d8dev/next-wp#4]
Hola! Mad props to your mad science! 🙌 . Thank you for this. So clean, well structured. I've read the WP GraphQL docs on authenticating requests. I wondered if you have a recommendation or pattern you'd suggest to authentication from the front-end to the WP backend? Hope this doesn't come off as lazy AF but rather a request for expert insights, not re-inventing the wheel for a newbie. Thanks for the consideration.

**Comment by youngbloodcyb** [comment]
Great question! 

This repo just uses the WP REST API which supports basic auth — https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

The requests on this app actually don't even require authentication since they are read only. Surprisingly even most big content sites using Wordpress don't protect their WP REST endpoint for reading content. 

A few examples of this are Wired magazine or TechCrunch. If you go to either site and append `/wp-json/wp/v2/posts` to the URL, you will get all of their posts back as JSON. You can even configure your `next-wp` site to literally just pull content from one of these publications. 

<img width="579" alt="Screenshot 2024-06-18 at 10 35 24 AM" src="https://github.com/9d8dev/next-wp/assets/95453018/6770d556-8209-4609-9d3d-cf892bd5b57c">


We opted to not use GraphQL in this project. We didn't see it as a huge need for a simple headless site. If we were to use WP more as an application backend, it would probably be great to add support for GraphQL to it so that it has greater flexibility

**Comment by youngbloodcyb** [comment]
I also failed to mention this in the previous comment, but since we're generating the pages statically, content only pulls from WP when the site builds. The load on the WP backend is pretty light since we're not always hitting it to serve content

**Comment by brijr** [comment]
Make sure as well to disable the WordPress front end and make sure that your Wordpress is non indexable. Your endpoint will be added via ENV and then the posts/authors/categories all will be statically generated.

**Comment by srizvi** [comment]
Thank you @youngbloodcyb and @brijr! Epic release, so helpful. Sorry for dropping off the face of the earth after your thoughtful comments and guidance. Much appreciated!
